#!/usr/bin/env python3
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path
from typing import Any

import torch


CERTIFICATE_THRESHOLDS = {
    "final_omega_6d": "Omega_6D",
    "final_omega_q": "Omega_Q",
    "final_amplitude_error": "epsilon_A",
    "final_probability_error": "epsilon_P",
    "final_phase_error": "phase_error",
    "final_exhaustive_error": "exhaustive_error",
    "final_closure_error": "closure_error",
    "normalization_error": "normalization_error",
}


def as_float(payload: dict[str, Any], key: str) -> float:
    if key not in payload:
        raise KeyError(f"missing certificate key: {key}")
    value = payload[key]
    if isinstance(value, torch.Tensor):
        value = value.detach().cpu().item()
    out = float(value)
    if not math.isfinite(out):
        raise ValueError(f"non-finite certificate value for {key}: {out}")
    return out


def as_bool(payload: dict[str, Any], key: str) -> bool:
    if key not in payload:
        raise KeyError(f"missing certificate key: {key}")
    return bool(payload[key])


def load_payload(path: Path) -> dict[str, Any]:
    payload = torch.load(str(path), map_location="cpu")
    if not isinstance(payload, dict):
        raise TypeError("state file does not contain a dictionary payload")
    if "amplitudes" not in payload:
        raise KeyError("state file does not contain amplitudes")
    return payload


def audit(path: Path, *, tau: float, require_certified_flag: bool) -> tuple[bool, list[str]]:
    payload = load_payload(path)
    amplitudes = torch.as_tensor(payload["amplitudes"]).to(torch.complex128)

    n = int(payload.get("n", round(math.log2(int(amplitudes.numel())))))
    expected_count = 2**n
    amplitude_count = int(amplitudes.numel())

    normalization_from_amplitudes = float((amplitudes.abs().pow(2).sum() - 1.0).abs().detach().cpu())

    lines: list[str] = []
    failures: list[str] = []

    lines.append(f"state={path}")
    lines.append(f"n={n}")
    lines.append(f"amplitude_count={amplitude_count}")
    lines.append(f"expected_amplitude_count={expected_count}")

    if amplitude_count != expected_count:
        failures.append(f"amplitude_count mismatch: {amplitude_count} != {expected_count}")

    if require_certified_flag:
        try:
            certified = as_bool(payload, "quantum_strong_certified")
        except Exception as exc:
            certified = False
            failures.append(str(exc))

        lines.append(f"quantum_strong_certified={certified}")

        if not certified:
            failures.append("quantum_strong_certified is not True")
    else:
        certified = bool(payload.get("quantum_strong_certified", False))
        lines.append(f"quantum_strong_certified={certified}")

    for key, label in CERTIFICATE_THRESHOLDS.items():
        try:
            value = as_float(payload, key)
        except Exception as exc:
            failures.append(str(exc))
            lines.append(f"{label}=MISSING")
            continue

        lines.append(f"{label}={value:.17g}")

        if value > tau:
            failures.append(f"{label} exceeds tau: {value:.17g} > {tau:.17g}")

    lines.append(f"normalization_from_amplitudes={normalization_from_amplitudes:.17g}")

    if normalization_from_amplitudes > tau:
        failures.append(
            "normalization_from_amplitudes exceeds tau: "
            f"{normalization_from_amplitudes:.17g} > {tau:.17g}"
        )

    if "amplitudes_with_phi" in payload:
        amplitudes_with_phi = torch.as_tensor(payload["amplitudes_with_phi"]).to(torch.complex128)
        born_with_phi = float((amplitudes_with_phi.abs().pow(2).sum() - 1.0).abs().detach().cpu())
        lines.append(f"born_with_phi_from_amplitudes={born_with_phi:.17g}")

        if born_with_phi > tau:
            failures.append(f"born_with_phi_from_amplitudes exceeds tau: {born_with_phi:.17g} > {tau:.17g}")

    closure_steps = payload.get("closure_steps_used", "NA")
    best_omega_eff = payload.get("best_omega_eff", "NA")
    last_omega_eff = payload.get("last_omega_eff", "NA")
    last_candidate = payload.get("last_candidate", "NA")

    lines.append(f"closure_steps_used={closure_steps}")
    lines.append(f"best_omega_eff={best_omega_eff}")
    lines.append(f"last_omega_eff={last_omega_eff}")
    lines.append(f"last_candidate={last_candidate}")

    ok = not failures
    lines.insert(0, f"CERTIFICATE_OK={ok}")

    if failures:
        lines.append("FAILURES:")
        lines.extend(f"- {item}" for item in failures)

    return ok, lines


def main() -> None:
    ap = argparse.ArgumentParser(description="Audit CTNet Hilbert Projector strong certificate .pt state")
    ap.add_argument("state", help="Path to a .pt state generated by solve_ising_cubo6d_only.py")
    ap.add_argument("--tau", type=float, default=1e-6, help="Certification threshold")
    ap.add_argument(
        "--no-require-certified-flag",
        action="store_true",
        help="Do not fail if quantum_strong_certified is absent or false",
    )
    args = ap.parse_args()

    ok, lines = audit(
        Path(args.state),
        tau=float(args.tau),
        require_certified_flag=not args.no_require_certified_flag,
    )

    for line in lines:
        print(line)

    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
