#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

import torch


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from ctnet_hilbert_projector.projective_engine import CTNetProjectiveState


def branch_z(index: int, site: int) -> int:
    return 1 if ((index >> site) & 1) else -1


def branch_u_count(index: int) -> int:
    return int(index).bit_count()


def load_probabilities(path: Path, *, with_phi: bool) -> tuple[CTNetProjectiveState, torch.Tensor]:
    st = CTNetProjectiveState.load(path)
    bank = st.amplitudes_with_phi if with_phi else st.amplitudes
    probs = bank.abs().pow(2).to(torch.float64)
    return st, probs


def expectation_z(probs: torch.Tensor, n: int, site: int) -> float:
    total = 0.0
    for idx, p in enumerate(probs.detach().cpu().tolist()):
        total += float(p) * branch_z(idx, site)
    return total


def expectation_zz(probs: torch.Tensor, n: int, i: int, j: int) -> float:
    total = 0.0
    for idx, p in enumerate(probs.detach().cpu().tolist()):
        total += float(p) * branch_z(idx, i) * branch_z(idx, j)
    return total


def sector_masses(probs: torch.Tensor, n: int) -> list[float]:
    sectors = [0.0 for _ in range(n + 1)]
    for idx, p in enumerate(probs.detach().cpu().tolist()):
        sectors[branch_u_count(idx)] += float(p)
    return sectors


def adjacent_pairs(n: int) -> list[tuple[int, int]]:
    return [(i, i + 1) for i in range(n - 1)]


def all_pairs(n: int) -> list[tuple[int, int]]:
    return [(i, j) for i in range(n) for j in range(i + 1, n)]


def compute_observables(path: Path, *, with_phi: bool, pair_mode: str) -> dict[str, Any]:
    st, probs = load_probabilities(path, with_phi=with_phi)
    n = st.n

    if probs.numel() != 2**n:
        raise ValueError(f"amplitude_count={probs.numel()} incompatible with n={n}")

    norm = float(probs.sum().detach().cpu())
    norm_error = abs(norm - 1.0)

    z_values = {f"Z_{i}": expectation_z(probs, n, i) for i in range(n)}
    magnetization_z = sum(z_values.values()) / float(n)

    if pair_mode == "none":
        pairs: list[tuple[int, int]] = []
    elif pair_mode == "adjacent":
        pairs = adjacent_pairs(n)
    elif pair_mode == "all":
        pairs = all_pairs(n)
    else:
        raise ValueError(f"pair_mode invalido: {pair_mode}")

    zz_values = {f"Z_{i}Z_{j}": expectation_zz(probs, n, i, j) for i, j in pairs}
    sectors = sector_masses(probs, n)

    return {
        "state": str(path),
        "n": n,
        "amplitude_count": int(probs.numel()),
        "with_phi": bool(with_phi),
        "normalization": norm,
        "normalization_error": norm_error,
        "magnetization_z": magnetization_z,
        "Z": z_values,
        "ZZ": zz_values,
        "sector_mass_by_u_count": {str(k): v for k, v in enumerate(sectors)},
    }


def print_text(result: dict[str, Any]) -> None:
    print(f"state={result['state']}")
    print(f"n={result['n']}")
    print(f"amplitude_count={result['amplitude_count']}")
    print(f"with_phi={result['with_phi']}")
    print(f"normalization={result['normalization']:.17g}")
    print(f"normalization_error={result['normalization_error']:.17g}")
    print(f"magnetization_z={result['magnetization_z']:.17g}")

    for key, value in result["Z"].items():
        print(f"<{key}>={value:.17g}")

    for key, value in result["ZZ"].items():
        print(f"<{key}>={value:.17g}")

    for key, value in result["sector_mass_by_u_count"].items():
        print(f"sector_mass_u_count_{key}={value:.17g}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Measure projective u/p observables from a CTNet .pt state")
    ap.add_argument("state", help="Path to .pt state generated by solve_ising_cubo6d_only.py")
    ap.add_argument("--with-phi", action="store_true", help="Use amplitudes with Cubo global phase applied")
    ap.add_argument("--pairs", choices=["none", "adjacent", "all"], default="adjacent")
    ap.add_argument("--json", action="store_true", help="Emit JSON")
    args = ap.parse_args()

    result = compute_observables(Path(args.state), with_phi=args.with_phi, pair_mode=args.pairs)

    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
    else:
        print_text(result)


if __name__ == "__main__":
    main()
