#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from ctnet_hilbert_projector.projective_engine import CTNetProjectiveState


def wrap_phase(x: float) -> float:
    return math.atan2(math.sin(x), math.cos(x))


def read_phase_pair(
    state: CTNetProjectiveState,
    sigma: str,
    tau: str,
    *,
    with_phi: bool,
) -> dict[str, Any]:
    a_sigma = state.amplitude(sigma, with_phi=with_phi)
    a_tau = state.amplitude(tau, with_phi=with_phi)

    p_sigma = (a_sigma.real * a_sigma.real) + (a_sigma.imag * a_sigma.imag)
    p_tau = (a_tau.real * a_tau.real) + (a_tau.imag * a_tau.imag)

    theta_sigma = math.atan2(a_sigma.imag, a_sigma.real)
    theta_tau = math.atan2(a_tau.imag, a_tau.real)
    delta_theta = wrap_phase(theta_sigma - theta_tau)

    cos_delta = math.cos(delta_theta)
    sin_delta = math.sin(delta_theta)
    overlap_weight = math.sqrt(max(0.0, p_sigma * p_tau))
    interference_kernel = overlap_weight * cos_delta
    quadrature_kernel = overlap_weight * sin_delta

    return {
        "sigma": sigma,
        "tau": tau,
        "with_phi": bool(with_phi),
        "A_sigma_real": a_sigma.real,
        "A_sigma_imag": a_sigma.imag,
        "A_tau_real": a_tau.real,
        "A_tau_imag": a_tau.imag,
        "P_sigma": p_sigma,
        "P_tau": p_tau,
        "Theta_sigma": theta_sigma,
        "Theta_tau": theta_tau,
        "DeltaTheta": delta_theta,
        "cos_DeltaTheta": cos_delta,
        "sin_DeltaTheta": sin_delta,
        "sqrt_P_sigma_P_tau": overlap_weight,
        "interference_kernel": interference_kernel,
        "quadrature_kernel": quadrature_kernel,
    }


def default_pairs(n: int) -> list[tuple[str, str]]:
    return [
        ("u" * n, "p" * n),
        ("up" * (n // 2) + ("u" if n % 2 else ""), "pu" * (n // 2) + ("p" if n % 2 else "")),
    ]


def parse_pair(text: str) -> tuple[str, str]:
    if ":" not in text:
        raise argparse.ArgumentTypeError("cada par debe tener formato sigma:tau")
    sigma, tau = text.split(":", 1)
    sigma = sigma.strip()
    tau = tau.strip()
    if not sigma or not tau:
        raise argparse.ArgumentTypeError("sigma y tau no pueden estar vacios")
    return sigma, tau


def compute_phase_report(path: Path, pairs: list[tuple[str, str]], *, with_phi: bool) -> dict[str, Any]:
    st = CTNetProjectiveState.load(path)

    if not pairs:
        pairs = default_pairs(st.n)

    rows = [
        read_phase_pair(st, sigma, tau, with_phi=with_phi)
        for sigma, tau in pairs
    ]

    return {
        "state": str(path),
        "n": st.n,
        "with_phi": bool(with_phi),
        "pair_count": len(rows),
        "pairs": rows,
    }


def print_text(report: dict[str, Any]) -> None:
    print(f"state={report['state']}")
    print(f"n={report['n']}")
    print(f"with_phi={report['with_phi']}")
    print(f"pair_count={report['pair_count']}")

    for row in report["pairs"]:
        sigma = row["sigma"]
        tau = row["tau"]
        print(f"pair={sigma}:{tau}")
        print(f"{sigma}.A.real={row['A_sigma_real']:.17g}")
        print(f"{sigma}.A.imag={row['A_sigma_imag']:.17g}")
        print(f"{tau}.A.real={row['A_tau_real']:.17g}")
        print(f"{tau}.A.imag={row['A_tau_imag']:.17g}")
        print(f"{sigma}.P={row['P_sigma']:.17g}")
        print(f"{tau}.P={row['P_tau']:.17g}")
        print(f"{sigma}.Theta={row['Theta_sigma']:.17g}")
        print(f"{tau}.Theta={row['Theta_tau']:.17g}")
        print(f"DeltaTheta({sigma},{tau})={row['DeltaTheta']:.17g}")
        print(f"cos_DeltaTheta({sigma},{tau})={row['cos_DeltaTheta']:.17g}")
        print(f"sin_DeltaTheta({sigma},{tau})={row['sin_DeltaTheta']:.17g}")
        print(f"sqrt_P_sigma_P_tau({sigma},{tau})={row['sqrt_P_sigma_P_tau']:.17g}")
        print(f"interference_kernel({sigma},{tau})={row['interference_kernel']:.17g}")
        print(f"quadrature_kernel({sigma},{tau})={row['quadrature_kernel']:.17g}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Measure projective phase and interference kernels from CTNet u/p .pt state")
    ap.add_argument("state", help="Path to .pt state generated by solve_ising_cubo6d_only.py")
    ap.add_argument("pairs", nargs="*", type=parse_pair, help="Pairs in sigma:tau form, e.g. uuuuuu:pppppp")
    ap.add_argument("--with-phi", action="store_true", help="Use amplitudes with Cubo global phase applied")
    ap.add_argument("--json", action="store_true", help="Emit JSON")
    args = ap.parse_args()

    report = compute_phase_report(Path(args.state), args.pairs, with_phi=args.with_phi)

    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print_text(report)


if __name__ == "__main__":
    main()
