#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from ctnet_hilbert_projector.projective_engine import CTNetProjectiveState


def wrap_phase(x: float) -> float:
    return math.atan2(math.sin(x), math.cos(x))


def default_branches(n: int) -> list[str]:
    branches = [
        "u" * n,
        "p" * n,
        "up" * (n // 2) + ("u" if n % 2 else ""),
        "pu" * (n // 2) + ("p" if n % 2 else ""),
    ]

    out: list[str] = []
    for branch in branches:
        if branch not in out:
            out.append(branch)
    return out


def branch_readout(st: CTNetProjectiveState, sigma: str, *, with_phi: bool) -> dict[str, float]:
    a = st.amplitude(sigma, with_phi=with_phi)
    p = (a.real * a.real) + (a.imag * a.imag)
    theta = math.atan2(a.imag, a.real)

    return {
        "A_real": float(a.real),
        "A_imag": float(a.imag),
        "P": float(p),
        "Theta": float(theta),
    }


def pair_kernel(left: dict[str, float], right: dict[str, float]) -> dict[str, float]:
    delta = wrap_phase(left["Theta"] - right["Theta"])
    cos_delta = math.cos(delta)
    sin_delta = math.sin(delta)
    sqrt_pp = math.sqrt(max(0.0, left["P"] * right["P"]))

    return {
        "DeltaTheta": delta,
        "cos_DeltaTheta": cos_delta,
        "sin_DeltaTheta": sin_delta,
        "sqrt_P_sigma_P_tau": sqrt_pp,
        "interference_kernel": sqrt_pp * cos_delta,
        "quadrature_kernel": sqrt_pp * sin_delta,
    }


def compute_matrix(
    path: Path,
    branches: list[str],
    *,
    with_phi: bool,
) -> dict[str, Any]:
    st = CTNetProjectiveState.load(path)

    if not branches:
        branches = default_branches(st.n)

    for branch in branches:
        if len(branch) != st.n:
            raise ValueError(f"branch {branch!r} has length {len(branch)}, expected n={st.n}")
        bad = sorted(set(branch) - {"u", "p"})
        if bad:
            raise ValueError(f"branch {branch!r} contains invalid symbols: {bad}")

    readouts = {
        sigma: branch_readout(st, sigma, with_phi=with_phi)
        for sigma in branches
    }

    matrix: dict[str, dict[str, dict[str, float]]] = {}
    for sigma in branches:
        matrix[sigma] = {}
        for tau in branches:
            matrix[sigma][tau] = pair_kernel(readouts[sigma], readouts[tau])

    return {
        "state": str(path),
        "n": st.n,
        "with_phi": bool(with_phi),
        "branch_count": len(branches),
        "branches": branches,
        "readouts": readouts,
        "matrix": matrix,
    }


def print_matrix(report: dict[str, Any], key: str) -> None:
    branches = report["branches"]
    print(key)
    print("row\\col " + " ".join(branches))

    for sigma in branches:
        values = [
            f"{report['matrix'][sigma][tau][key]:.17g}"
            for tau in branches
        ]
        print(f"{sigma} " + " ".join(values))


def print_text(report: dict[str, Any]) -> None:
    print(f"state={report['state']}")
    print(f"n={report['n']}")
    print(f"with_phi={report['with_phi']}")
    print(f"branch_count={report['branch_count']}")
    print("branches=" + ",".join(report["branches"]))

    for sigma in report["branches"]:
        r = report["readouts"][sigma]
        print(f"{sigma}.A.real={r['A_real']:.17g}")
        print(f"{sigma}.A.imag={r['A_imag']:.17g}")
        print(f"{sigma}.P={r['P']:.17g}")
        print(f"{sigma}.Theta={r['Theta']:.17g}")

    print_matrix(report, "DeltaTheta")
    print_matrix(report, "cos_DeltaTheta")
    print_matrix(report, "sin_DeltaTheta")
    print_matrix(report, "interference_kernel")
    print_matrix(report, "quadrature_kernel")


def main() -> None:
    ap = argparse.ArgumentParser(description="Measure a projective coherence matrix over selected u/p branches")
    ap.add_argument("state", help="Path to .pt state generated by solve_ising_cubo6d_only.py")
    ap.add_argument("branches", nargs="*", help="Branches, e.g. uuuuuu pppppp upupup puupup")
    ap.add_argument("--with-phi", action="store_true", help="Use amplitudes with Cubo global phase applied")
    ap.add_argument("--json", action="store_true", help="Emit JSON")
    args = ap.parse_args()

    report = compute_matrix(Path(args.state), args.branches, with_phi=args.with_phi)

    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print_text(report)


if __name__ == "__main__":
    main()
