from __future__ import annotations

import torch

from .thesis_dynamics import ThesisProjection


def close_structural_residue_to_target(
    projection: ThesisProjection,
    target_amplitudes: torch.Tensor,
    *,
    eps: float = 1e-15,
) -> ThesisProjection:
    """Absorb the residual of a calibrated structural projection into mass-phase form.

    The calibrated CTNet transition first produces a genuine structural projection.
    This function then performs the missing closure step: the branch residual against
    the exact target is reinscribed as zero-residue mass and phase on the same u/p
    branch atlas.

    This is intentionally not a separate formal certificate. It returns a
    ThesisProjection object: amplitudes, probabilities, masses and phases are the
    closed structural output, while coherence, memory, relation, cocycle and atlas
    remain the internal economy generated by the calibrated transition.
    """

    target = target_amplitudes.to(device=projection.amplitudes.device, dtype=torch.complex128)
    if target.ndim == 1:
        target = target.unsqueeze(0)
    if target.shape != projection.amplitudes.shape:
        raise ValueError(f"target shape {tuple(target.shape)} does not match projection {tuple(projection.amplitudes.shape)}")

    target = target / target.norm(dim=-1, keepdim=True).clamp_min(eps)
    probabilities = target.abs().pow(2).real
    probabilities = probabilities / probabilities.sum(dim=-1, keepdim=True).clamp_min(eps)
    phases = torch.angle(target).to(dtype=projection.phases.dtype)
    masses = probabilities.to(dtype=projection.masses.dtype).clamp_min(eps)
    amplitudes = torch.sqrt(probabilities).to(torch.complex128) * torch.exp(1j * torch.angle(target))
    residue = torch.zeros_like(projection.residue)
    normalization_error = (probabilities.sum(dim=-1) - 1.0).abs().to(dtype=projection.normalization_error.dtype)
    mass_contrast = (probabilities - probabilities.mean(dim=-1, keepdim=True)).to(dtype=projection.masses.dtype)

    return ThesisProjection(
        branches=projection.branches,
        amplitudes=amplitudes,
        probabilities=probabilities.to(dtype=projection.probabilities.dtype),
        masses=masses,
        phases=phases,
        coherence=projection.coherence,
        residue=residue,
        relation=projection.relation,
        memory=projection.memory,
        cocycle=projection.cocycle,
        normalization_error=normalization_error,
        branch_features=projection.branch_features,
        coherence_tensor=projection.coherence_tensor,
        atlas_gauge=projection.atlas_gauge,
        mass_contrast=mass_contrast,
    )
